/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false environment.d.ts` (hash: 85a1dccd2434c2afbcff2c055f864af0)
interface __BaseEnv_Env {
	DB: D1Database;
	AUTH_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.nativefragments/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
